### ISSUE TITLE
maximal feature set compatible with proxy-polyfill

### ISSUE THREAD

**Issue by lukeburns** [nx-js/observer-util#20]
i'm exploring the possibility of implementing the maximum feature set of observer-util compatible with https://github.com/GoogleChrome/proxy-polyfill, which only works for get, set, apply, construct traps. 

it's severely limited. it would restrict use to observing predefined properties (as the polyfill is unable to intercept new properties), and handling arrays would be slow (it would require replacing the entire array every change), but i think there are use cases where developers can work under reasonable constraints that would allow at least for a working implementation in e.g. IE11, even if slow.

i understand this library has opinion and likely no interest in supporting IE, but if i find myself interested in such an implementation, i wonder what challenges you would anticipate.

**Comment by solkimicreb** [comment]
I expect it to work out of the box for the supported subset of traps with one exception. The Proxy polyfill seems to throw an exception for unsupported traps at a first glance. That will probably cause an issue, and you may have to fork it or send a PR to make this configurable.

Please not that this really limits the possible usage though, `has` and `delete` operations and dynamic props are just part of the picture. You will use array support (without a hack) and object enumeration support too (as they rely on dynamic props).

**Comment by lukeburns** [comment]
Forked, replaced type errors with warnings, implemented some really nasty array handling, and it works — out of the box (for the most part)! https://github.com/lukeburns/proxy-polyfill
