### ISSUE TITLE
Scheduler with Task

### ISSUE THREAD

**Issue by chrismbeckett** [nx-js/observer-util#27]
I am building native web components with Lit-Html and want to minimize unnecessary re-rendering calls. I am not sure I quite understand how the scheduler feature works. I have created a Scheduler that uses a Set, as per the example to eliminate duplicate reactions, and `setTimeout` to create a task that defers processing.

```
class Scheduler {
  constructor() {
    this.timer = null;
    this.reactions = new Set();
  }
  add(value) {
    this.reactions.add(value);
    if (this.timer) clearTimeout(this.timer);
    this.timer = setTimeout(() => {
      this.reactions.forEach(reaction => reaction());
    });
  }
  delete(value) {
    this.reactions.delete(value);
  }
}
```

This seems to work, and results in batching reactions and generating a single render. Is this a suitable way to accomplish this, or is there a simpler way?

FYI - the delete method never seems to get called.

**Comment by solkimicreb** [comment]
You got the concept of schedulers right. You just made a deduplicating async scheduler. 🙂 

The delete method is called when you `unobserve` an observed function that is still scheduled to be run (by an async scheduler). This does not happen frequently in most use cases.

You can also try https://github.com/nx-js/queue-util for a bit more complex scheduler. It's main idea is the same as your's but it has multiple priorities for the tasks and it can be started, stopped and flushed by hand if needed.

**Comment by chrismbeckett** [comment]
Awesome, thank you. I did look at the queue-util, and it certainly seems like a good option when I get to coordinating changes to application-level state.
