### ISSUE TITLE
Unidirectional Data Flow

### ISSUE THREAD

**Issue by chrismbeckett** [nx-js/observer-util#28]
I am having a difficult time reasoning how using this library will work when I am passing data down a stack of web components.

Let's say I have an array of items at a top-level component that I have wrapped as observable. I need to pass that array down to child components (through a JavaScript property). The child component also wraps the property as observable.

a) Since I want to keep the web component interface agnostic of using the proxy for reactivity, should I be passing the *raw* object down to the child components rather than the proxied object?
b) Will duplicate proxies be created for each web component as the array is passed down, or does the library detect its the same object and reuse a single proxy?
c) If I change the array at the high-level component, will it only trigger the observe() within that web component, or will the observe() methods fire at every web component I passed the array down to automatically as well? (I am concerned that it fires at every level, but then also fires again as the stack is re-rendered down from the top-level component).

I am hoping I am explaining this correctly - this is a difficult scenario to describe but unidirectional data flow is a proven architecture and something I really need to work with native web components.

**Comment by solkimicreb** [comment]
Hi!

Generally you would like to wrap objects once with observable and use that observable object in functions (components). Functions are triggered when the observable data they rely on changes.

If the functions are in a parent child relation (in the same sync stack), things get more complicated. The above rule still stands though, every function is triggered which uses a piece of mutated observable data. If you wrap every single function of the stack (parent, child, grandchild) all of them will be triggered once, meaning the grandchild will run 3 times (once from the parent run, once from the child run and once in itself.)

You have several options:

## Only wrap the top level component with `observe`

This is not the way to go. You would like to get granular and minimal automatic re-renders from this library. This one would only give you one big re-render on all related observable data mutations.

 ## Wrap all components with observe

Do not directly call sub components as functions from parent components and wrap all of them with `observe`. This is something similar to what popular frameworks do, it makes sure that only necessary pieces of view are re-rendered.

## Wrap all components and keep calling the child directly from the parent render

You can get rid of unnecessary renders with the usage of custom schedulers. They are really recommended for every non super trivial use case. The idea of schedulers is this: the lib only notifies you if am observed function should run, because the data it depends on changed, but it does not run the function. You can then decide when and how many times you would like to run that function. In this case you can hand pick the components that you really think should be re-rendered.

## My suggestion

In my opinion you should definitely go with options 2 and custom schedulers.

I hope this helped slightly, let me know if you need more clarification. (A repo link or some code would really help btw.)

**Comment by chrismbeckett** [comment]
I really appreciate the reply. Here is the simplest code snippet I can come up with to demonstrate how I was trying to use this library.

```
class MyComponent extends HTMLElement {
  static get observedAttributes() { return ['msg']; }

  constructor() {
    this.state = observable({});
    this.ready = false;
  }

  get msg() { return raw(this.state['msg']); }
  set msg(val) { this.state['msg'] = val; }

  attributeChangedCallback(name, prev, curr) {
    if (this.state[name] != curr) this.state[name] = curr;
  }

  connectedCallback() {
    if (!this.ready) {
      observe(() => this.renderCallback(), {scheduler: new Scheduler()});
      this.ready = true;
    }
  }

  renderCallback() {
    this.setAttribute('msg', this.state.msg);
    const tmpl = html`
       <p>${this.state.msg}</p>
   `;
    render(tmpl, this);
  }
}
```

Basically, the internal state of the web component can be populated by JavaScript properties, attributes, or internally by the component. Any change to the state should trigger a re-render. The rendered template may include child custom elements where parts of the state are then passed down to the child element as a property or attribute. Each web component and its state needs to be autonomous/independent from the others, and data is passed down through properties or attributes. 

There doesn't seem to be anyway to *sandbox* this library to just within the context of a single web component. The rendering of the parent template (which is inside of an observe function), triggers a mutation of a child observable data structure by setting a property on the child, and throws the "Mutating observables in reactions is forbidden." error on the child component.

The only way I can see this library working is if a single observed data store is injected directly into all the web components through a global context or singleton (rather than passed down as a parent>child property). This would avoid needing to pass the observed data structure as a property in a template, and would allow every component to observe a reaction simultaneously and independently from each other. While this scenario can work, it sort of violates the true principle of native web components where all state has to be passed as an attribute or property on the element, a pure top-down pattern (unidirectional or otherwise).

I can see this library working for your Option #1 where only the top-level component has an observable application store that triggers a top-down re-render to child components that just get raw data, and I will likely continue to use it in that capacity for shared application state.

Unless you have a way to sandbox the observable/observer so it can be used independently inside each web component, it looks like I will need to code my own Proxy for detecting changes to the internal state of each component.

**Comment by solkimicreb** [comment]
These are my general view on your points:

- Web components can only pass string primitives around as attributes (props). If you go with web components, you won't be able to pass around anything more complex between components (You could JSON.stringify/parse, but it is still pretty limited and slow).
- You are using two reactivity systems together (observer-util and web component's `observedAttributes`). You should cleanly separate the two. I would use nx-observe for the state and `observedAttributes` for the attributes.
- You have the same piece of data exposed in multiple places. The general rule of thumb is to encapsulate the state and expose the props. State is for local data props is for data form the outside world. For exampe:
  - Exposing `this.state.msg` on `this.msg` is probably not a good idea.
  - Copying the state into the props is probably not a good idea: `this.setAttribute('msg', this.state.msg);`
  - Exposing the props on the `this` directly is something you could do though.

I don't think you will have an issue with the reactivity and sandboxing, but I need to see an example with at least two levels (parent and child component) to see what's the issue.

This is a modified version of your code with all the tips from above:

```js
// you don't have to create new scheduler for every component
// later on you can create a priority based smart renderer by having a few different schedulers
// and picking the right one for each component
const scheduler = new Scheduler();

class MyComponent extends HTMLElement {
  static get observedAttributes() { return ['msg']; }

  // exposing the state on `this` is an anti-pattern, but exposing the attributes is a common thing
  // examples are standard HTML attributes and React props
  get msg() { return this.getAttribute('msg'); }
  set msg(val) { this.setAttribute('msg') }

  constructor() {
    this.state = observable({});
  }

  connectedCallback() {
    if (!this.observedCallback) {
      this.observedRender = observe(() => this.renderCallback(), { scheduler });
    }
  }

  // make sure to clean up on disconnect (remove all the reactive wiring with `unobserve`)
  // to avoid memory leaks
  disconnectedCallback () {
    unobserve(this.observedRender);
    this.observedRender = undefined;
  }

  attributeChangedCallback(name, prev, curr) {
    // state and attributes are the two data sources, when the attributes change we should also
    // trigger a re-render
    // instead of calling `observedRender` directly, add it to the scheduler to avoid duplicates
    // in cases where both a state and an attribute change is triggering the same render as an example
    if (prev !== curr) {
      // make sure to use `observedRender` here instead of `renderCallback`, this lets the observer-util
      // to properly track the render and react on state changes later on
      // (it tracks new code, which was previously hidden behind conditional branches)
      scheduler.add(this.observedRender)
    }
    // you can also pass data from the attribute to the state here, if needed
  }

  renderCallback() {
    const tmpl = html`<p>${this.state.msg}</p>`;
    render(tmpl, this);
  }
}
```

I hope this helps 🙂

**Comment by chrismbeckett** [comment]
a) Lit-Html has an extended version that passes data using JavaScript properties rather than attributes, so you don't have to use attributes.

b) State is state, whether it is passed in through properties, attributes or is internal. I was demonstrating a tiny contrived sample because I don't want to past 2000 lines of code into an issue that is just intended to demonstrate an issue.

c) Whether state is coming in through JavaScript properties (that can mirror to attributes), attributes, or private/protected internals, I need to be able to react to changes on all of it. Using one internal observable data structure to store all of it was the point, not whether I was exposing it on *this*. In real life, I use a symbol with a named property `this[$state]` so the data object that backs properties, attributes and private state is not on the public interface. That is irrelevant to whether your observe utility works in this situation or not.

c) I was demonstrating using attributeChangedCallback to sync to an observable state/property bag exactly so I don't have to try and deal with two observable systems separately which is messy. Instead I was demonstrating that I sync a local type-converted variable in my state data structure and keep it synched with attributes.

d) I already have a custom base element that automating the generation of all the boilerplate for synching JavaScript properties with attributes, etc. Once again, I am not pasting hundreds of lines of code into an issue to argue semantics with you.

It seems like you are just obfuscating the issue rather than addressing the limitations in your library. Your experience also seems limited to React.

**Comment by solkimicreb** [comment]
No need to be so offended. I am trying to help and I can't do it without a proper code example. If you send me an example with multiple components I can help you out with the library. If you don't want to use this library, don't use it.
