### ISSUE TITLE
Mutating observables in reactions is forbidden

### ISSUE THREAD

**Issue by chrismbeckett** [nx-js/observer-util#29]
I don't understand why I am getting this error. The code where I am mutating the observable is not in a reaction? Here is a sample of what is happening in a custom element.

```
// create observable store
this.store = observable({
  clickCount: 0,
  clickTimestamp: null
});

// re-render component with async/dedupe Scheduler
observe(() => {
  this.renderCallback();
}, {scheduler: new Scheduler()});

// event handler mutating props
this.addEventListener('click', (e) => {
  this.store.clickCount = this.store.clickCount + 1;
  this.store.clickTimestamp = Date.now(); // <== I GET THE ERROR HERE
})
```

I am getting the error trying to set the second property on the observable.

**Comment by solkimicreb** [comment]
Can you also send the code in `renderCallback()`? I don't see any issues the code you sent.

**Comment by chrismbeckett** [comment]
Sorry, I had a circular looping problem with updating attributes from properties which was firing the attributeChangedCallback on customer elements, which was changing the property. I had a guard clause for this but had a type conversion/comparison bug.
