### ISSUE TITLE
4.2.0 broke something

### ISSUE THREAD

**Issue by mendrik** [nx-js/observer-util#30]
I have been using version 4.1.3 without any problems, but when I tried 4.2.0 my model updates were not propagated downwards anymore. Is there something that changed when render() is called? reverting back to 4.1.3 fixed the issue. 

I have code like this
```
 <InputPassword changes={v => loginModel.password = v}
   name="password"
   value={loginModel.password}
   big={true}/>
```
and my model is imported from
```
const loginModel = observable(new LoginForm())
export {loginModel}
```

I receive the new `v` values but when the component re-renders value hasn't changed.
I use it with preact but it's basically almost the same as react-easy-state

Any idea what is breaking it?

**Comment by solkimicreb** [comment]
Can you check that you don't accidentally have two separate versions (4.1.3 and 4.2.0) in your node modules?

**Comment by mendrik** [comment]
omg that was it I have a helper dependency and I updated it only there. sorry for wasting your time!

**Comment by solkimicreb** [comment]
No worries 🙂 This is kind of a common thing, I think I will add a console warning when this happens.
