### ISSUE TITLE
Understanding reactions

### ISSUE THREAD

**Issue by ciaoben** [nx-js/observer-util#38]
Why this behavior?

```
import { observable, observe } from "@nx-js/observer-util";

// This WORK
const counter = observable({ num: 0 });
const countLogger = observe(() => console.log("a-", counter.num));

// this calls countLogger and logs 1
counter.num++;
setTimeout(() => {
  // this calls countLogger and logs 4
  counter.num = 4;
}, 2 * 1000);

// This NOT WORK
const counter2 = observable({ num: 0 });
const countLogger2 = observe(() => console.log("b-", counter));

// this calls countLogger and logs 1
counter2.num++;
setTimeout(() => {
  // this calls countLogger and logs 4
  counter2.num = 4;
}, 2 * 1000);

// Output
//  a- 0
// a- 1
// b- Object {num: 1}
// a- 4
```

Why does observing `counter` instead of `counter.num` break the behavior?

Here is a [sandbox](https://codesandbox.io/s/o902313yw5)

**Comment by solkimicreb** [comment]
If you use a property inside a reaction in any *JS* way and change it later in any way *JS* the reaction will re-run. console.log is an edge case that runs none JS code internally (it iterates all properties but not with interceptible JS code). Try to change `console.log("b-", counter)` to `console.log("b-", JSON.stringify(counter))` and see what happens. `JSON.stringify` runs standard JS code internally which results in reaction re-runs on property changes. This behavior is something that I don't intend to change and it is pretty much related to console.log only. Other built-in methods and intercepted. I hope this helps.
