### ISSUE TITLE
Observing through a Proxy

### ISSUE THREAD

**Issue by k1w1** [nx-js/observer-util#47]
Thanks for a fantastic library. So elegant!

I am trying to use it in a scenario where I have another proxy in order to make the object more elegant to use. I want to create an object which acts like an array, but also stores other data. However observe() doesn't flow through the proxy. I am not surprised it doesn't work, but I am looking for ideas on how to make it work.

```javascript
import { observable, observe } from '@nx-js/observer-util';

class Foo {
  constructor() {
    this._collection = [111]

    return new Proxy(this, {
      get(target, prop, receiver) {
        if (prop in target._collection)
          return target._collection[prop]
        else {
          return Reflect.get(target, prop, receiver);
        }
      },
      has(target, prop) {
        if (prop in target._collection) {
          return true
        } else {
          return Reflect.has(target, prop)
        }
      }
    })
  }

  get data() {
    return this._collection
  }
}

const counter = observable(new Foo);
const workingObserve = observe(() => console.log(`Working: ${counter.data[0]}`));
const notWorkingObserve = observe(() => console.log(`Not working: ${counter[0]}`));

counter._collection = [1,2,3]
counter._collection = [7,8]
```

Note that the `notWorkingObserve` function is not executed when the collection is updated.

I am testing by just running this code in https://repl.it/languages/babel

**Comment by solkimicreb** [comment]
Try to replace `return target._collection[prop]` with `return Reflect.get(target._collection, prop, receiver._collection)` in the `get` trap. That should fix it.

I suggest you to read the Proxy, exotic object and ordinary object related parts of the [EcmaScript spec](http://www.ecma-international.org/ecma-262/6.0/) to fully understand Proxy traps and JS get/set operations. It's not an easy read but I found no article that really explains these in the required depth.

As a rule of thumb, whenever you return something from a Proxy trap make sure to do it with the `Reflect` equivalent that forwards **all of the arguments** (or their custom transformed variants) of the Proxy trap.

**Comment by k1w1** [comment]
Yes, that works. Thanks for the help and the advice.
