### ISSUE TITLE
Integration with React-Native using proxy-polyfill

### ISSUE THREAD

**Issue by SukantGujar** [nx-js/observer-util#7]
React-Native [doesn't support Proxy](http://stackoverflow.com/questions/38871456/es6-proxy-not-defined-in-react-native-when-not-in-remote-debug-mode) at the moment. We have been trying to use [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill), but it doesn't support the entire capabilities of native proxy. Wanted to take your opinion on what could be broken as a result of this.

Thanks!

**Comment by solkimicreb** [comment]
Ouch, Proxies can't be polyfilled. The polyfills are using getter/setters (just like mobx). This means that expando properties, delete operations and loops won't work. `for of` loops can be hacked around to work, but the rest is impossible to do as far as I know.

**Comment by solkimicreb** [comment]
I can look into adding an internal mobx like fallback when Proxies are not available. The fallback would display a warning. If it is using the fallback, you would need to use predefined stores just like with mobx to avoid expando props.

**Comment by SukantGujar** [comment]
😯 the product I am working on aims to have cross platform flux store. 

I am following up with RN team on this. Apparently, only Android devices and iOS 9 and lower are impacted. They use iOS8 JSC engine on Android, which doesn't have native Proxies among several other things. We cannot afford to lose Android platform.

Looks like JS disparities will never stop haunting us... Hate to look out for another store simply because I am stuck in a time where RN hasn't updated JSC in over two years...

The features which cannot be polyfilled are what give nx-observe the edge over Mobx. The only alternative I am left with is to go back to immutable based store which will screw up member access simplicity. Imagine `store.auth.user` vs `store.getIn(["auth", "user"])`. 😞 

The greatest irony would be by the time the product is out, native Proxy maybe supported in some form in RN 😒.

**Comment by solkimicreb** [comment]
I know, it is really a struggle. I think your original issue with mobx (conditionals not being observed) is fixed though. It has nothing to do with proxies. Maybe you could give it another go.

**Comment by SukantGujar** [comment]
Compared to nx-observe, I find MobX complicated to work with. Things like expandos which are key to our application work ootb here, while we had several scary moments with `extendObservable`. The fact is, Proxy makes meta programming much easier than earlier workarounds, plain and simple.

**Comment by solkimicreb** [comment]
I am closing this issue now. I will open a more general issue for partial legacy platform support when I have some time. (Full support for pre ES6 platforms is not possible.)

Thanks for opening it though, I didn't know that RN uses an old JSC on Android.

**Comment by SukantGujar** [comment]
Sure, thanks for all the help and support you provided during my tryst with nx-observe. Its a wonderful library and I am eagerly hoping it sees wide usage.

We have been able to adapt our code to use MobX for the time being, but like I said, its not as transparent and so we have kept the dependencies to a minimum to allow us to switch over to nx-observe when RN starts supporting it.

**Comment by solkimicreb** [comment]
Thx for all the support and bug finds. It was extremely helpful!
I will let you know, if I make some kind of legacy feature.
